# goal definition
float64 min_angle
float64 max_angle
float64 tilt_rate
---
# result definition
teleop_msgs/CompressedPointCloud2 scan
---
# feedback definition
float64 percent_complete
duration time_remaining
